source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CircleSlider_Example', :exclusive => true do
  pod "CircleSlider", :path => "../"
end

target 'CircleSlider_Tests', :exclusive => true do
  pod "CircleSlider", :path => "../"

  
end
